# ==========================================
# NOMBRE DEL MICROSERVICIO
# ==========================================

spring.application.name=servicio-camiones

# ==========================================
# PUERTO DEL MICROSERVICIO
# ==========================================

server.port=8084

# ==========================================
# CONFIGURACIÓN POSTGRESQL / NEON
# ==========================================

spring.datasource.url=jdbc:postgresql://ep-mute-silence-aqf2jlq3-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_2CgulSTydBO3

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN HIBERNATE / JPA
# ==========================================

# update = crea/actualiza tablas sin borrar datos
spring.jpa.hibernate.ddl-auto=update

# Dialecto PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SWAGGER / OPENAPI
# ==========================================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true